default: &default
adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development2

test:
  <<: *default
  database: recipe_app_test1

production:
  <<: *default
  database: recipe_app_production
  username: recipe_app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
